import type { Product, Category } from './types';

export const DEMO_CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Rings',
    slug: 'rings',
    image: 'https://placehold.co/400x300/B8860B/ffffff?text=Rings',
    productCount: 2,
  },
  {
    id: '2',
    name: 'Necklaces',
    slug: 'necklaces',
    image: 'https://placehold.co/400x300/B8860B/ffffff?text=Necklaces',
    productCount: 2,
  },
  {
    id: '3',
    name: 'Earrings',
    slug: 'earrings',
    image: 'https://placehold.co/400x300/B8860B/ffffff?text=Earrings',
    productCount: 2,
  },
  {
    id: '4',
    name: 'Bracelets',
    slug: 'bracelets',
    image: 'https://placehold.co/400x300/B8860B/ffffff?text=Bracelets',
    productCount: 2,
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'aurelle-22k-gold-ring',
    name: 'Zainab 22K Gold Ring',
    description: 'Exquisite handcrafted 22K gold ring with intricate traditional patterns. Perfect for weddings and special occasions.',
    price: 8500000, // ₹85,000 in paise
    mrp: 8500000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Gold',
    purity: '22K',
    category: 'Rings',
    images: [
      'https://placehold.co/800x800/B8860B/ffffff?text=Gold+Ring+1',
      'https://placehold.co/800x800/DAA520/ffffff?text=Gold+Ring+2',
    ],
    stock: 5,
    weight: 12.5,
    featured: true,
    reviews: [
      {
        id: 'r1',
        customerName: 'Priya Sharma',
        rating: 5,
        comment: 'Absolutely stunning! The craftsmanship is impeccable.',
        createdAt: '2026-08-01T10:30:00Z',
      },
      {
        id: 'r2',
        customerName: 'Rahul Verma',
        rating: 5,
        comment: 'Bought this for my wife. She loves it!',
        createdAt: '2026-08-05T14:20:00Z',
      },
    ],
  },
  {
    id: '2',
    slug: 'diamond-solitaire-pendant',
    name: 'Diamond Solitaire Pendant',
    description: 'Classic diamond solitaire pendant set in 18K white gold. Certified IGI diamond with excellent cut and clarity.',
    price: 15000000, // ₹1,50,000
    mrp: 15000000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Diamond',
    purity: '18K',
    category: 'Necklaces',
    images: [
      'https://placehold.co/800x800/E5E5E5/333333?text=Diamond+Pendant+1',
      'https://placehold.co/800x800/F0F0F0/333333?text=Diamond+Pendant+2',
    ],
    stock: 3,
    weight: 8.2,
    featured: true,
    reviews: [
      {
        id: 'r3',
        customerName: 'Anjali Patel',
        rating: 5,
        comment: 'The sparkle is mesmerizing! Worth every penny.',
        createdAt: '2026-07-28T16:45:00Z',
      },
      {
        id: 'r4',
        customerName: 'Vikram Singh',
        rating: 4,
        comment: 'Beautiful piece, delivery was quick.',
        createdAt: '2026-08-10T11:15:00Z',
      },
    ],
  },
  {
    id: '3',
    slug: 'pearl-drop-earrings',
    name: 'Pearl Drop Earrings',
    description: 'Elegant freshwater pearl drop earrings with 92.5% sterling silver hooks. Perfect for evening wear.',
    price: 2500000, // ₹25,000
    mrp: 2500000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Pearl',
    purity: '92.5%',
    category: 'Earrings',
    images: [
      'https://placehold.co/800x800/F5F5DC/8B4513?text=Pearl+Earrings+1',
      'https://placehold.co/800x800/FFFAF0/8B4513?text=Pearl+Earrings+2',
    ],
    stock: 10,
    weight: 4.5,
    reviews: [
      {
        id: 'r5',
        customerName: 'Kavita Reddy',
        rating: 5,
        comment: 'Lightweight and elegant. Great quality pearls!',
        createdAt: '2026-08-03T09:30:00Z',
      },
      {
        id: 'r6',
        customerName: 'Neha Gupta',
        rating: 5,
        comment: 'Perfect for daily wear. Highly recommended!',
        createdAt: '2026-08-07T13:40:00Z',
      },
    ],
  },
  {
    id: '4',
    slug: 'gold-bangle-set',
    name: 'Gold Bangle Set',
    description: 'Set of 4 traditional 22K gold bangles with fine filigree work. A timeless addition to your collection.',
    price: 12000000, // ₹1,20,000
    mrp: 12000000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Gold',
    purity: '22K',
    category: 'Bracelets',
    images: [
      'https://placehold.co/800x800/FFD700/8B4513?text=Gold+Bangles+1',
      'https://placehold.co/800x800/FFA500/8B4513?text=Gold+Bangles+2',
    ],
    stock: 4,
    weight: 45.0,
    featured: true,
    reviews: [
      {
        id: 'r7',
        customerName: 'Meera Iyer',
        rating: 5,
        comment: 'Absolutely gorgeous! Traditional and elegant.',
        createdAt: '2026-07-25T15:20:00Z',
      },
      {
        id: 'r8',
        customerName: 'Sunita Desai',
        rating: 5,
        comment: 'The filigree work is amazing. Very satisfied!',
        createdAt: '2026-08-12T10:00:00Z',
      },
    ],
  },
  {
    id: '5',
    slug: 'platinum-chain',
    name: 'Platinum Chain',
    description: 'Premium platinum chain with contemporary design. Hypoallergenic and perfect for daily wear.',
    price: 6500000, // ₹65,000
    mrp: 6500000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Platinum',
    category: 'Necklaces',
    images: [
      'https://placehold.co/800x800/E5E4E2/000000?text=Platinum+Chain+1',
      'https://placehold.co/800x800/F5F5F5/000000?text=Platinum+Chain+2',
    ],
    stock: 7,
    weight: 15.0,
    reviews: [
      {
        id: 'r9',
        customerName: 'Aditya Kumar',
        rating: 4,
        comment: 'Good quality platinum. Looks premium.',
        createdAt: '2026-08-02T12:30:00Z',
      },
      {
        id: 'r10',
        customerName: 'Rohan Mehta',
        rating: 5,
        comment: 'Exceeded expectations. Very happy!',
        createdAt: '2026-08-09T16:50:00Z',
      },
    ],
  },
  {
    id: '6',
    slug: 'ruby-stud-earrings',
    name: 'Ruby Stud Earrings',
    description: 'Natural ruby stud earrings set in 18K yellow gold. Vibrant color and excellent clarity.',
    price: 4500000, // ₹45,000
    mrp: 4500000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Ruby',
    purity: '18K',
    category: 'Earrings',
    images: [
      'https://placehold.co/800x800/E0115F/FFD700?text=Ruby+Earrings+1',
      'https://placehold.co/800x800/DC143C/FFD700?text=Ruby+Earrings+2',
    ],
    stock: 6,
    weight: 3.8,
    reviews: [
      {
        id: 'r11',
        customerName: 'Divya Nair',
        rating: 5,
        comment: 'The rubies are so vibrant! Love them!',
        createdAt: '2026-07-30T14:10:00Z',
      },
      {
        id: 'r12',
        customerName: 'Pooja Joshi',
        rating: 4,
        comment: 'Beautiful earrings, good packaging.',
        createdAt: '2026-08-11T09:20:00Z',
      },
    ],
  },
  {
    id: '7',
    slug: 'kundan-necklace',
    name: 'Kundan Necklace',
    description: 'Exquisite Kundan necklace with traditional Rajasthani craftsmanship. Adorned with semi-precious stones.',
    price: 9500000, // ₹95,000
    mrp: 9500000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Mixed',
    purity: '22K',
    category: 'Necklaces',
    images: [
      'https://placehold.co/800x800/FF6347/FFD700?text=Kundan+Necklace+1',
      'https://placehold.co/800x800/FF4500/FFD700?text=Kundan+Necklace+2',
    ],
    stock: 2,
    weight: 55.0,
    featured: true,
    reviews: [
      {
        id: 'r13',
        customerName: 'Lakshmi Menon',
        rating: 5,
        comment: 'This is a masterpiece! The craftsmanship is unreal.',
        createdAt: '2026-07-26T11:00:00Z',
      },
      {
        id: 'r14',
        customerName: 'Radha Krishna',
        rating: 5,
        comment: 'Perfect for my wedding. Thank you Zainab Jewellers!',
        createdAt: '2026-08-08T17:30:00Z',
      },
    ],
  },
  {
    id: '8',
    slug: 'silver-anklet',
    name: 'Silver Anklet',
    description: 'Traditional 92.5% sterling silver anklet with delicate bell charms. Comfortable for everyday wear.',
    price: 1500000, // ₹15,000
    mrp: 1500000,
    hsnCode: '7113',
    gstRate: 3,
    metal: 'Silver',
    purity: '92.5%',
    category: 'Bracelets',
    images: [
      'https://placehold.co/800x800/C0C0C0/333333?text=Silver+Anklet+1',
      'https://placehold.co/800x800/D3D3D3/333333?text=Silver+Anklet+2',
    ],
    stock: 12,
    weight: 18.5,
    reviews: [
      {
        id: 'r15',
        customerName: 'Shreya Pillai',
        rating: 5,
        comment: 'Beautiful sound from the bells! Love it.',
        createdAt: '2026-08-04T10:15:00Z',
      },
      {
        id: 'r16',
        customerName: 'Aarti Chopra',
        rating: 4,
        comment: 'Good quality silver, comfortable fit.',
        createdAt: '2026-08-13T12:45:00Z',
      },
    ],
  },
];
